- README.md
- plugin.xml
- www/browser/Media.js
Implementation for [CB-7962](https://issues.apache.org/jira/browse/CB-7962)
> CB-7962 Adds browser platform support

- src/wp/AudioPlayer.cs
- src/wp/Media.cs
- www/Media.js
https://issues.apache.org/jira/browse/CB-8779
> CB-8779 Fixed media status reporting on wp8

- src/wp/AudioPlayer.cs
- tests/tests.js
https://issues.apache.org/jira/browse/CB-8793
> CB-8793 Fixed tests to pass on wp8 and windows

- src/windows/MediaProxy.js
Fix for https://issues.apache.org/jira/browse/CB-8888
> CB-8888 Makes media status reporting on windows more precise

- src/ios/CDVSound.h
- src/ios/CDVSound.m
- tests/tests.js
- www/Media.js
This is refered to https://issues.apache.org/jira/browse/CB-8098
Adds playback change rate feature (setRate) for iOS. To add it it Android and WP it seems not quite easy.
> Add Media.prototype.setRate method (only for iOS)

- tests/tests.js
https://issues.apache.org/jira/browse/CB-9619
> CB-9619 Fixed tests waiting for precise position

- plugin.xml
- src/android/AudioHandler.java
- src/android/PermissionHelper.java
Left out of the first round by mistake
> CB-10455 android: Adding permission helper to remove cordova-android 5.0.0 constraint

- .gitignore
- .jshintrc
- .travis.yml
- README.md
- package.json
- src/blackberry10/index.js
- src/tizen/MediaProxy.js
- src/windows/MediaProxy.js
- tests/tests.js
- www/Media.js
- www/browser/Media.js
[Jira issue](https://issues.apache.org/jira/browse/CB-10636)
> CB-10636 Add JSHint for plugins

- src/android/AudioPlayer.java
Android
Fixes a crash and enables asynchronous MediaPlayer error handling.
The crash was happening because the plugin wasn't catching the error from Android's MediaPlayer and thus when the error (in this case, [MEDIA_ERROR_TIMED_OUT](https://developer.android.com/reference/android/media/MediaPlayer.html#MEDIA_ERROR_TIMED_OUT)) occurred, the plugin wasn't aware of this and tried to send new commands to the MediaPlayer which was causing the crash.
Manual and automatic mobilespec tests on Android 4.4 emulator.
> CB-11655 (Android) Enabled asynchronous error handling

- .appveyor.yml
- .travis.yml
- tests/tests.js
- www/browser/Media.js
Browser
Enables AppVeyor and Travis to run tests on browser platform
See AppVeyor and Travis results under this PR
> CB-13028 (CI) Browser builds on Travis and AppVeyor

- README.md
> CB-12264 (README): fix media.getCurrentAmplitude definition

- .travis.yml
> CB-13751: Add build-tools-26.0.2 to travis

- .travis.yml
- tests/tests.js
Tests code only
Browser (test)
iOS (test)
Removing Browser's play audio tests. (which fails)
Change test streaming mp3 file's url in iOS tests.
> CB-14091: fix tests code for stream url and remove browser

- README.md
Add parameters type in error and status callback.
> README: add parameters type in error and status callback.

- .travis.yml
- types/index.d.ts
> fix(types): Add type definition for getCurrentAmplitude

- .github/workflows/android.yml
- .github/workflows/chrome.yml
- .github/workflows/ios.yml
- .github/workflows/lint.yml
- tests/tests.js
> ci: add gh-actions workflows

- package-lock.json
- package.json
- plugin.xml
- tests/package.json
- tests/plugin.xml
n/a
Prepare for major changes by bumping plugin version to 6.0.0-dev
bump package and plugin version
n/a
> chore: bump version to 6.0.0-dev

- src/android/AudioPlayer.java
android
missing parenthesis from #328
added missing parenthesis
> fix(android): missing parenthesis from #328

- src/ios/CDVSound.m
ios
* Split task from #196
* Rebased #196 with current main branch.
See #196 for more details
n/a
> fix(ios): set rate with current playback rate

- README.md
- src/android/AudioHandler.java
- src/android/AudioPlayer.java
- tests/tests.js
- www/Media.js
android
* Split task from #196
* Rebased #196 with current main branch.
* Updates README to describe API requirement for setRate.
* Reverted & updated the `Media.prototype.setRate` conditional check to include `Android`.
* The plugin also supports the Windows & Browser platforms but `setRate` was never previously mentioned to support those platforms.
Closes #196
Closes #296
Closes #152
Resolves #223
See #196 for more details
n/a
> feat(android): add setRate

- src/android/AudioPlayer.java
- tests/tests.js
Android
resolves #117
See #117
- GH Actions
Failures appear to be only on GH Actions but passes manually.
> feat(android): add 'message' field to media error CB-11641

- package-lock.json
- package.json
- plugin.xml
- tests/package.json
- tests/plugin.xml
n/a
Prepare for 6.1.0 minor release
Bump version in various files.
n/a
> chore: bump version to 6.1.0-dev

- package-lock.json
- package.json
- plugin.xml
android
Use latest file plugin and support Android 13 (SDK 33)
* Bump `cordova-plugin-file` dependency to `8.0.0`
* Bump `cordova-android` requirement to `>=12.0.0`
`npm t`
> feat(android)!: bump file & android requirements

- src/ios/CDVSound.m
> (fix) typo in CDVSound.m
