apache/cordova-plugin-media

- plugin.xml
Media plugin by default requests musicLibrary capability but it's not using it. It should be removed since, it's not required.
> CB-8686 - remove musicLibrary capability

- tests/tests.js
https://issues.apache.org/jira/browse/CB-8793
Sometimes (on a slow emulators) spec.16 still fails because it couldn't start playing in time. This fixes it.
> CB-8793 Increased playback timeout in tests

- src/android/AudioPlayer.java
I´ve came across a use case where i always get a NullPointerException:
1 - Start recording audio file
2 - Stop recording
3 - Play the recorded file
When the recording ends, the status is set to "MEDIA_STOPPED", if i try to play the recorded file right afterwards, a NullPointerException is thrown at line 494 of readyPlayer(...). This happens because the file name is the same as the audioFile, and the corresponding switch/case assumes that in this case it means that this particular file has already been played before, which is not true. At this point there is no "player" object but only a "recorder", therefore the exception. With a simple check on the recorder and player it is possible to play the newly recorded file without any issues.
On IOS there is no issue with this use case, only …
> fix record and play NullPointerException

- src/wp/AudioPlayer.cs
- tests/tests.js
This fixes [CB-9605](https://issues.apache.org/jira/browse/CB-9605)
In case of playing remote file, specified by URL (instead of local path) `player.Source.AbsolutePath` is a last part of original URL and thus `AbsolutePath.LastIndexOf(filePath)` always -1:
AbsoluteUri = "http://cordova.apache.org/downloads/BlueZedEx.mp3"
AbsolutePath = "/downloads/BlueZedEx.mp3"
So, using an `AbsoluteUri` looks more reasonable and works for both local files and remote URLs.
> CB-9605 Fixes issue with playback resume after pause on WP8

- plugin.xml
- src/ios/CDVSound.h
- src/ios/CDVSound.m
This fixes 2 issues in the Cordova Jira, both with iOS.  It enables streaming support for media playback from URLs while retaining the existing playback for local media.
The second part is the simply background thread the play function so it doesn't block the ui or lock up the app on load.  Gets rid of some of those pesky warnings in xcode too.
Tested with simulator and on iphone 5 and iphone 6 and ipad 2, with iOS 8.1, 8.3 & 8.4
Please merge these and bump the version of the media plugin so I can stop installing them from my own fork :)
Fix for CB-57
Updated to use avplayer when url starts with http:// or https:// for
full streaming support.
All other urls will use the standard AVAudioplayer
Fix for CB-8222
Background thread on play to prevent locking during initial load of
media.
> Streaming & Background threading on play

- tests/tests.js
All
The PR changes audio stream URL used in tests to be allowed to play on Windows in order to make media.spec.25 'should be able to play an audio stream' passing on Windows
Ran auto tests for all main platforms
> CB-11429 Update infinite audio stream URL in tests

- src/android/AudioPlayer.java
Android
https://issues.apache.org/jira/browse/CB-11754
Fixes a build-time error introduced in https://github.com/apache/cordova-plugin-media/commit/4d7aabb74a39bdfad0969915377e73106803cdf8
Built and run an application for Android
> CB-11754 (Android) Fixed the build error

- src/ios/CDVSound.m
iOS
Fixes a crash by ensuring that the avPlayer is in correct state before invoking seekTo.
Bug reproduced and fix tested by running automatic tests on iPad 2 with iOS 8.1
> CB-10849 (ios) Fixed a crash when playing soundfiles consecutively

- README.md
- plugin.xml
ios
Removes the MICROPHONE_USAGE_DESCRIPTION preference and documents how to use edit-config to do the same
> CB-13265 Remove ios usage description from media plugin

- src/android/AudioPlayer.java
android
Resolving recording audio issue.
1. File.renameTo method used in AudioPlayer.java can not move file across partitions.
Then  I developed copying the file by using i/o stream when renameTo failing.
2. media.stopRecord() in JS calls stopRecording in Java,
However media.release() in JS also calls stopRecording in Java via destroy method.
The second call of stopRecording overrides the audio file with empty. 
This PR prevents the unnecessary call of stopRecording.
sample code is 
```
var fileName = "test.aac";
var myMedia = {};
var myStatus = null;
function recordMedia(){
myMedia = new Media(cordova.file.dataDirectory + fileName, function (msg) {
console.log("Success:", msg);
}, function (e) {
console.error("Error:", e);
myMedia.release();
myStatus = Media.MEDIA_NONE;
}, function …
```
> CB-12849: checking mediaState in destroy method, and moving file by stream when renameTo failing

- .travis.yml
- src/ios/CDVSound.m
iOS
Calls iOS>=10 API to prevent waiting for the media stream to buffer before playing
tests pass
> CB-13445 (iOS) Streaming media can take up to 8-10 seconds to start

- www/Media.js
All (www change)
This removes the javascript reference to released media objects.  See #248 
Add a success callback to delete media id after it is released by platform specific code.
- [NA ] I added automated test coverage as appropriate for this change
- [ NA] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [Y ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [NA ] I've updated the documentation if necessary
> Fix #248 delete javascript reference to released media

- tests/tests.js
Browser (Test Specs)
Test failing due to Chrome's Autoplay Policy
This PR disables test case 21, 22, and 27 because these calls `play()` method which is against Chrome's Autoplay Policy.
**The Error:**
> Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
**The Reason:**
> The Autoplay Policy launched in Chrome 66 for audio and video elements and is effectively blocking roughly half of unwanted media autoplays in Chrome. For the Web Audio API, the autoplay policy launched in Chrome 71. This affects web games, some WebRTC applications, and other web pages using audio features. More details can be found in the Web Audio API section below.
- CI
> test(browser): disable test cases w/ play() due to Autoplay Policy

- .eslintrc.yml
- package-lock.json
- package.json
- Resolve NPM Aduit Warnings
- Bump `@cordova/eslint-config@^4.0.0`
- Resolve lint warnings by allowing `var`. Support older devices.
- Rebuild `package-lock.json` to update all `@cordova/eslint-config` sub-dependencies.
- `npm t`
> dep: bump @cordova/eslint-config@4.0.0 w/ fix & package-lock rebuild

- src/android/AudioPlayer.java
As stated in issue #325, it looks like PR #317 missed a spot in the corrections it was making.  This commit adds that fix to the missed location. You can find more info in #325.
Android
Fixes #325.
When debugging through the plugin code, I was able to determine that when a simple file name is provided for the media.startRecord() API a file path is eventually generated in the createAudioFilePath() method using either getExternalFilesDir() or getCacheDir(). In my emulator, it creates a temporary file path like the following: /storage/emulated/0/Android/data/com.<org>.<appName>/files/tmprecording-###.3gp. (The logic for creating this temporary file path was updated in PR #317.)
However, when a simple file name is provided to the media.play() API, a different file path is created instead. The …
> fix(android): issue #325

- tests/tests.js
- www/Media.js
Removes references to removed platforms. Should have been part of #157. Depends on #283.
> fix: remove deprecated platform code snippets 

- plugin.xml
* Android
The plugin uses the `OnAudioFocusChangeListener` to listen to audio focus changes such as the ones that happen on incoming calls. There is no need to request the `android.permission.READ_PHONE_STATE` because it is not needed.
I think it's good to remove such permission because it has a _dangerous_ protection level.
Removed `<uses-permission android:name="android.permission.READ_PHONE_STATE" />` frrom `plugin.xml`
> fix(android): remove READ_PHONE_STATE permission

- src/ios/CDVSound.m
- iOS
- Adds an error call for stalled playback on iOS.
Physical device testing on:
- iPhone X (iOS 12)
- iPhone 6 (iOS 11)
> Add error call for stalled_playback (iOS only)

- plugin.xml
Android
Drop the `WRITE_EXTERNAL_STORAGE` permission declaration since its **protection level** is **dangerous**.
Closes #316
Removed the `WRITE_EXTERNAL_STORAGE` permission declare from `plugin.xml`
> feat(android): drop WRITE_EXTERNAL_STORAGE permission

- src/ios/CDVSound.m
iOS platform
In iOS, this plugin does not support `file://` scheme.
Therefore following code does not work
```
window.requestFileSystem(
LocalFileSystem.PERSISTENT,
0,
function (fs) {
const pathPrefix = fs.root.toURL();
file = pathPrefix + fileName;
mediaRec = new Media(file, mediaRecordSuccess, mediaError, mediaRecordStatus);
mediaRec.startRecord();
},
function (err) {
alert("LocalFileSystem Error");
}
);
```
On the other hand, this code works in Android.
The actual `file` variable in the above code is like `file:///var/mobile/Containers/Data/Application/6DAC6E88-C38A-4A8B-A7E9-456345E5D25D/Library/NoCloud/myrecording.m4a` where the `file://` scheme is used.
But the current this plugin does not support `file://` scheme in iOS and not work in iOS.
This is inconsistent with in Android. …
> feat(ios): support file scheme

- src/ios/CDVSound.m
ios
resolves #165
→ CB-13852
See #165
> fix(ios): error on getPosition when time is nan

- tests/tests.js
test
GH Actions CI appears to hit timeout limits.
I made sure the done function was called in success callback, if called, objects cleared in both before and after each, and set the jasmine default timeout to match against the playback test timeout.
Manual and GH Actions: 
- https://github.com/erisu/cordova-plugin-media/actions/runs/2962107380
- https://github.com/erisu/cordova-plugin-media/actions/runs/2962107378
> test(spec.timeout): try to improve against timeout failures

- tests/tests.js
test
GH Actions CI Test against iOS 13 was failing to determin if the audio was seeked.
Manually testing the seeking feature while audio is playing worked but appears to have a race condition with in the CI for iOS 13.
I changed the behavior of the test to pause the audio immediately after seeking before getting the current position to confirm that it seeked.
Manual and GH Actions
> test(spec.22): pause media before calling getCurrentPosition

- src/ios/CDVSound.m
ios
resolves #147
This PR cherry-picks commit from #147 on an up-to-date branch of current main branch.
See #147 for more detail
> fix(ios): Reset default audio session category when release (CB-13243)

- package-lock.json
- package.json
- src/windows/MediaProxy.js
- tests/tests.js
n/a
- Use latest eslint configurations
- Resolve audit warnings
- bump `@cordova/eslint-config@5.0.0`
- applied lint auto corrections
`npm t`
> dep(dev)!: bump @cordova/eslint-config@5.0.0

- src/android/AudioHandler.java
android
Check for and request for permissions based on Android versions.
All Android versions will check for `RECORD_AUDIO` permission. If the permission is not missing (not granted), it will request for permission.
If Android SDK is less then 33, also check for `WRITE_EXTERNAL_STORAGE`. Request for the permission if missing.
Closes #380
Closes #374
Resolves #373
- refactored the `promptForRecord` method
- removed excessive methods.
- Created Cordova default project
- Added plugin.
- Tested recording functionality.
- Tested playing the file that was created from the tested recording.
- Confirmed that the temporary audio file name `tmprecording-<KEY>.3gp` was renamed to the specified filename.
> feat(android): support Android 13 permission checks and requests

- src/android/AudioPlayer.java
Android
Improve audio recording quality
Closes #331 
Note: This PR is setting the bitrate to 96 Kbps and not 128 Kbps. This plugin uses the AAC encoder, which generally provides better quality audio at a lower bitrate compared against MP3 encoder. While researching acceptable bitrate of AAC compared against MP3, some suggest using 96 Kbps for AAC while MP3 would be 128 Kbps. But this does not mean it is identical. In terms of quality, it will always result in source and equiptment.
Increased following settings:
- Audio BitRate -> `96000` (96 Kbps)
- Audio Sampling Rate -> `44100` (44.1 kHz)
- Tested recording audio on Google Pixel 6a (Android 13) device.
> feat(android): increase audio encoding bitrate and sampling rate

- src/ios/CDVSound.h
- src/ios/CDVSound.m
ios
Able to load media file paths that are written in custom scheme+hostname format or with a leading slash to represent root directory of "www"
Updated conditional checks
```js
// const mediaFile = "https://www...wav";
// const mediaFile = cordova.file.applicationDirectory + '/www/media/test.wav';
// const mediaFile = 'app://localhost/media/test.wav';
const mediaFile = '/media/test.wav';
const myMedia = new Media(mediaFile, onSuccess, onError);
myMedia.play();
```
> feat(ios): load media files with custom scheme+hostname and leading directory paths

- README.md
android
Add `WRITE_EXTERNAL_STORAGE` permission quirks to `README`.
n/a
> doc(android): add quirks for WRITE_EXTERNAL_STORAGE permission
